# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GiboWrapper < Formula
  desc "gibo-wrapper acts like gibo to improve gibo by adding the following features"
  homepage "https://tamada.github.com/gibo-wrapper"
  version "0.5.7"
  license "Unlicense license"

  depends_on "gibo"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tamada/gibo-wrapper/releases/download/v0.5.7/gibo-wrapper_Darwin_x86_64.tar.gz"
      sha256 "cbd1678518a1339f43380ce21f83a4acdef56b9954a707ca61651ebd5e72c4fc"

      def install
        bin.install "gibo-wrapper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tamada/gibo-wrapper/releases/download/v0.5.7/gibo-wrapper_Darwin_arm64.tar.gz"
      sha256 "7ab631c7a4ffacb46bac4ab45db71c277a0e43af677ae22105e55d03d94379b4"

      def install
        bin.install "gibo-wrapper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tamada/gibo-wrapper/releases/download/v0.5.7/gibo-wrapper_Linux_arm64.tar.gz"
      sha256 "6d8015ef96cd7673bbb2c5bfb2a5238bbb5a915c8f72957bdc597de404327bcb"

      def install
        bin.install "gibo-wrapper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tamada/gibo-wrapper/releases/download/v0.5.7/gibo-wrapper_Linux_x86_64.tar.gz"
      sha256 "31bf40166e43a6268efee19fa65d103fd399d4bf84c6bb33907502ea15ccca29"

      def install
        bin.install "gibo-wrapper"
      end
    end
  end
end
