# typed: false
# frozen_string_literal: true
VERSION="0.6.0"

# This file was generated by GoReleaser. DO NOT EDIT.
class GiboWrapper < Formula
  desc "gibo-wrapper acts like gibo to improve gibo by adding the following features"
  homepage "https://github.com/tamada/gibo-wrapper"
  version "0.6.0"
  license "Unlicense license"

  option "without-completions", "Disable bash completions"
  depends_on "bash-completion@2" => :optional
  depends_on "gibo"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tamada/gibo-wrapper/releases/download/v#{VERSION}/gibo-wrapper_#{VERSION}_darwin_amd64.tar.gz"
      sha256 "f608f0b96eb0f0619e45ccda79b8efe32fb357d1eb9a093cf10f38bef8515a75"
    end
    if Hardware::CPU.arm?
      url "https://github.com/tamada/gibo-wrapper/releases/download/v#{VERSION}/gibo-wrapper_#{VERSION}_darwin_arm64.tar.gz"
      sha256 "8170333fcb06936cdd6a284ea71b986ff1bb08d1b779aefa7a807f8404e02eda"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tamada/gibo-wrapper/releases/download/v#{VERSION}/gibo-wrapper_#{VERSION}_linux_arm64.tar.gz"
      sha256 "b63b3efd36119f540572006d60544dad3137c30a419d8bdc9954986c9fa69648"
    end
    if Hardware::CPU.intel?
      url "https://github.com/tamada/gibo-wrapper/releases/download/v#{VERSION}/gibo-wrapper_#{VERSION}_linux_amd64.tar.gz"
      sha256 "1c2c31f7b17c925b95243a3bb8d70dcfc771098229272ded9fd7191eb2c0de58"
    end
  end
  def install
    bin.install "gibo-wrapper"
    prefix.install "README.md"
    prefix.install "LICENSE"

    bash_completion.install   "completions/bash/gibo" if build.with? "completions"
    zsh_completion.install    "completions/zsh/_gibo" if build.with? "completions"
    fish_completion.install   "completions/fish/gibo" if build.with? "completions"
    elvish_completion.install "completions/elvish/gibo" if build.with? "completions"
  end

  def caveats
    <<~EOS
      Put the following alias setting into your shell configuration file.
          alias gibo='gibo-wrapper $@'
    EOS
  end
end
